### ISSUE TITLE
Cannot login after logging out

### ISSUE THREAD

**Issue by larrasu** [atinux/nuxt-todo-passkeys#4]
Steps to reproduce:
1. Create an account
2. Logout
3. Login

Error: `User verification required, but user could not be verified`

**Comment by atinux** [comment]
Do you mind recording a video to showcase? I cannot reproduce

**Comment by larrasu** [comment]
https://github.com/user-attachments/assets/ddfa7227-6620-4e98-9d53-9499e4947f03

**Comment by atinux** [comment]
and if you click on sign in without entering the username?

**Comment by larrasu** [comment]
I'm getting the same error.

https://github.com/user-attachments/assets/1f66ab6b-ded5-4378-85c0-a37e0efdd6eb

**Comment by Gerbuuun** [comment]
The problem is that you're not performing any verification (touch ID, face ID, password etc.) which is set to `preferred` by default but is actually `required`.
It is a misconfiguration and also not exposed in the event handler yet so I'll look into a way to expose this (and fix ofc).

Most users will be prompted to verify but this is not happening for you it seems.
For now you can add this to your `defineWebAuthnAuthenticateEventHandler`:
```ts
getOptions: () => ({ userVerification: 'required' }),
```
This will force the device to ask for verification

**Comment by atinux** [comment]
Could you check again the demo @larrasu ?

**Comment by larrasu** [comment]
It works now. Thank you!
